title: Houquan Zhou
position: Ph.D. Student
affiliation: Soochow University
email: Jacob_Zhou (at) outlook.com

plugins:
  - jekyll-spaceship
  - jekyll-last-modified-at
  # - jekyll-analytics

keywords: minimal academic
description:
  PhD student [@SUDA-HLT](http://hlt.suda.edu.cn), Soochow University
canonical: https://cv.hqzhou.com

semantic_scholar: https://www.semanticscholar.org/author/Houquan-Zhou/50986473
google_scholar: https://scholar.google.com/citations?user=hJWovmAAAAAJ
# cv_link: ./assets/files/cv.pdf
github_link: https://github.com/Jacob-Zhou
arxiv_link: https://cv.hqzhou.com/arxiv

avatar: ./assets/img/avatar.jpg
favicon: ./assets/img/favicon.svg
# favicon: ./assets/img/favicon.png
# favicon_dark: ./assets/img/favicon-dark.png

# jekyll_analytics:
#   GoogleAnalytics:
#     id: UA-284490532-1

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENSE
